// Generated by Wrangler
interface CloudflareEnv {
  ASSETS: Fetcher;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_KEY: string;
  CLOUDFLARE_API_TOKEN: string;
  ALLEATO_DATABASE_ID: string;
  R2_BUCKET_NAME: string;
  FIREFLIES_API_KEY: string;
}