name = "alleato-comprehensive-api"
main = "workers/comprehensive-api-worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "alleato"
database_id = "fc7c9a6d-ca65-4768-b3f9-07ec5afb38c5"

[[r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "alleato-meeting-transcripts"

[[queues.producers]]
queue = "vectorization-queue"
binding = "VECTOR_QUEUE"

[ai]
binding = "AI"

[observability]
enabled = true